### ISSUE TITLE
Add Lazygit integration

### ISSUE THREAD

**Issue by kirillmorozov** [kirillmorozov/dotfiles#38]
Call lazygit from the editor to stage/commit/whatever and then continue normal editing after TUI is closed.

In Vim something like this works:

```vim
:!lazyvim
```

While in Helix this:

```toml
[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
```
